### ISSUE TITLE
Adjust the given backendBasepath without a tailing slash

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#178]
**User story**
When an API is configured with a `backendBasepath` like so: `http://my-api:8080/api` the API-Gateway at runtime behaves differently than having it configured with `http://my-api:8080/api/`. 

Assuming an API with the following operation:
```yaml
paths:
  /api/v1/some/operation:
    get:
      produces:
        - application/json
      parameters:
        - description: The numbers of items to return.
```

Without the tailing slash the backend service is called with:
`http://my-api:8080/api/v1/some/operation`
which is wrong!

When it is configured with the `/` the backend with:
`http://my-api:8080/api/api/v1/some/operation`
which is correct.

**To avoid this when using the APIM-CLI, the CLI should automatically add the tailing slash to the configured backendBasepath.**
